module.exports = (sequelize, DataTypes) => {
  const bcrypt = require('bcrypt')

  const User = sequelize.define('User', {
    name: DataTypes.STRING,
    email: DataTypes.STRING,
    password: DataTypes.STRING
  }, {
    paranoid: true,
    tableName: 'users',
    timestamps: true
  })

  User.associate = (models) => {
    User.hasMany(models.UserList, {
      sourceKey: 'id',
      foreignKey: 'user_id',
      as: 'lists'
    })
  }

  User.beforeCreate((user, options) => {
    const { password } = user;

    const salt = bcrypt.genSaltSync(5)

    const hashedPassword = bcrypt.hashSync(password, salt)

    console.log('Generated by user:beforeSave', hashedPassword)

    user.password = hashedPassword;
  })

  return User
}