const { Product } = require(`${__basedir}/app/models`)

module.exports = (sequelize, DataTypes) => {
  const bcrypt = require('bcrypt')

  const User = sequelize.define('User', {
    name: DataTypes.STRING,
    email: DataTypes.STRING,
    password: DataTypes.STRING
  }, {
    paranoid: true,
    tableName: 'users',
    timestamps: false
  })

  User.associate = (models) => {
    User.belongsToMany(models.Product, {
      as: 'products',
      through: 'UserProduct',
      foreignKey: 'user_id',
      otherKey: 'product_id'
    })
  }

  User.beforeCreate((user, options) => {
    const { password } = user;

    const salt = bcrypt.genSaltSync(5)

    const hashedPassword = bcrypt.hashSync(password, salt)

    console.log('Generated by user:beforeSave', hashedPassword)

    user.password = hashedPassword;
  })

  return User
}